name: theater
description: Actor framework for Dart. This package makes it easier to work with isolates, create clusters of isolates.
version: 0.2.21
repository: https://github.com/GlebBatykov/theater

environment:
  sdk: '>=3.0.0 <4.0.0'

# dependencies:

dev_dependencies:
  lints: ^5.1.1
  test: ^1.16.0
  async: ^2.8.2